/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Industrial Elegance Color Palette
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0edec",
        "surface-container-high": "#ebe7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#424846",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        outline: "#727876",
        "outline-variant": "#c2c8c4",
        "surface-tint": "#4b635c",
        primary: "#041d18",
        "on-primary": "#ffffff",
        "primary-container": "#1a322c",
        "on-primary-container": "#819b92",
        "inverse-primary": "#b1ccc3",
        secondary: "#5f5e59",
        "on-secondary": "#ffffff",
        "secondary-container": "#e5e2db",
        "on-secondary-container": "#65645f",
        tertiary: "#121b17",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#26302b",
        "on-tertiary-container": "#8d9891",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface-variant": "#e5e2e1",
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "spacing-unit": "8px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
      },
    },
  },
  plugins: [],
}